// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // For migrations (schema changes), we must use the direct connection (port 5432)
    // to bypass the connection pooler (port 6543) which Supabase uses.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },});
